# Dependabot configuration for vulnerability monitoring
# This is FREE for public repos and provides continuous monitoring

version: 2
updates:
  # Backend service
  - package-ecosystem: "npm"
    directory: "/figure-collector-backend"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "security"
    commit-message:
      prefix: "chore"
      include: "scope"

  # Frontend service
  - package-ecosystem: "npm"
    directory: "/figure-collector-frontend"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "security"

  # Page scraper service
  - package-ecosystem: "npm"
    directory: "/page-scraper"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "security"

  # Version manager service
  - package-ecosystem: "npm"
    directory: "/version-manager"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "security"

  # Docker base images
  - package-ecosystem: "docker"
    directory: "/figure-collector-backend"
    schedule:
      interval: "weekly"
    labels:
      - "docker"
      - "security"

  - package-ecosystem: "docker"
    directory: "/figure-collector-frontend"
    schedule:
      interval: "weekly"
    labels:
      - "docker"
      - "security"

  - package-ecosystem: "docker"
    directory: "/page-scraper"
    schedule:
      interval: "weekly"
    labels:
      - "docker"
      - "security"

  - package-ecosystem: "docker"
    directory: "/version-manager"
    schedule:
      interval: "weekly"
    labels:
      - "docker"
      - "security"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "ci/cd"
      - "dependencies"