# Dependabot configuration with smart grouping
# - Patch updates: grouped (non-breaking)
# - Dev dependency minor updates: grouped (lower risk)
# - Major updates: individual PRs (potentially breaking)
# - Production dependency minor updates: individual PRs (higher risk)

version: 2
updates:
  # GitHub Actions - group all (low risk, non-code)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "github-actions"
    groups:
      github-actions:
        patterns: ["*"]

  # npm dependencies - smart grouping
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
    groups:
      # Group all patch updates (0.0.x) - non-breaking by semver
      patch-updates:
        update-types: ["patch"]

      # Group minor updates for dev dependencies only (lower risk)
      dev-minor-updates:
        dependency-type: "development"
        update-types: ["minor"]

    # Individual PRs for:
    # - Major updates (all dependencies) - potentially breaking
    # - Minor updates for production dependencies - higher impact
    # - Security updates are never grouped (Dependabot default)

  # Docker base images - individual PRs (security critical)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "docker"
